rawdata_dir: /data/NHLBI_IDSS/rawdata/NHLBI-53 #### Update this path to your rawdata folder
result_dir: /data/NHLBI_IDSS/projects/NHLBI-53 #### Update this path to your project folder
hg38_fa: /data/OpenOmics/references/DeepSeq/hg38
